# list
print('============list============')
classNames = ['Jane','Michel','Jacke']
print(classNames)
classNamesL = len(classNames)
print(classNamesL)
print('第一个元素是',classNames[0])
print('计算索引最后一个元素是',classNames[classNamesL-1])
print('直接索引最后一个元素是',classNames[-1])
classNames.append('Bob')
print('添加之后的list',classNames)
classNames.insert(0,'Adom')
print('向0位置添加之后的list',classNames)
classNames.pop(1)
print('删除位置1后的元素',classNames)
classNames.pop()
print('删除list末尾的元素',classNames)
classNames[-1] = 'Jane'
print('替换list末尾的元素',classNames)
# 向元素中添加不同类型的元素
classNames.append(1)
classNames.append('string')
classNames.append(['list'])
classNames.append(None)
classNames.append(True)
classNames.append(1.23)
print('存在不同类型元素的list',classNames)
# tuple(元组)
print('============tuple(元组)============')
scripts = ('JAVA','SQL','Python','php')
print('tuple(元组):',scripts)
print('获取最后一个元素',scripts[-1])
# 定义一个元素的tuple
onlyTuple = (1,)
print('只有一个元素的tuple',onlyTuple)
# 可变的tuple
changeTuple = ([],)
print('可变的tuple',changeTuple)
changeTuple[0].append('Python')
print('添加一个元素',changeTuple)